const style = {
    header: [
        "bg-kuru",
        "block",
        "border-b",
        "border-kuru-darker",
        "border-solid",
        "py-2",
        "text-white",
    ].join(" "),
    container: [
        "container",
        "flex",
        "items-center",
        "mx-auto",
    ].join(" "),
    logo: [
        "hover:text-grey-light",
        "logo-typography",
        "no-underline",
        "text-2xl",
        "text-white",
        "transition",
    ].join(" "),
    menu: [
        "flex",
        "list-reset",
        "ml-10",
    ].join(" "),
    menuItems: [
        "hover:text-grey-light",
        "no-underline",
        "text-white",
        "transition",
    ].join(" "),
    search: [
        "flex",
        "items-center",
        "ml-5",
    ].join(" "),
    searchField: [
        "bg-white",
        "border-b",
        "border-kuru-darker",
        "border-l",
        "border-solid",
        "border-t",
        "m-0",
        "outline-none",
        "p-2",
        "rounded-bl",
        "rounded-tl",
        "w-64",
    ].join(" "),
    searchButton: [
        "bg-white",
        "border-b",
        "border-kuru-darker",
        "border-r",
        "border-t",
        "m-0",
        "p-2",
        "rounded-br",
        "rounded-tr",
        "text-grey-dark",
    ].join(" "),
    social: [
        "flex",
        "list-reset",
        "ml-5",
    ].join(" "),
    socialItems: [
        "hover:text-grey-light",
        "no-underline",
        "text-white",
        "text-xl",
        "transition",
    ].join(" "),
};
export default style;