const style = {
    logIn: [
        "border-2",
        "border-solid",
        "border-white",
        "hover:bg-grey-lighter",
        "hover:border-grey-lighter",
        "hover:text-kuru",
        "mr-4",
        "no-underline",
        "px-6",
        "py-2",
        "rounded",
        "text-white",
        "transition",
    ].join(" "),
    signUp: [
        "bg-white",
        "border-2",
        "border-solid",
        "border-white",
        "hover:bg-grey-lighter",
        "hover:border-grey-lighter",
        "no-underline",
        "px-6",
        "py-2",
        "rounded",
        "text-kuru",
        "transition",
    ].join(" "),
};
export default style;